version: 2.1

orbs:
  python: circleci/python@1.4.0

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/install-packages
      - python/install-packages:
          args: pytest
          pypi-cache: false
      - run:
          command: python3 -m pytest
          name: pytest unittests
      - run:
          command: python3 -m pytest --cov=git_inspector --cov-report xml
          name: pytest code coverage
      - store_artifacts:
          path: coverage.xml

workflows:
  main:
    jobs:
      - build-and-test
